### ISSUE TITLE
Add inputs for each of the buttons on the steering wheel

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/steering_wheel_module_23#1]
Make sure they are all labeled in a way that is easy to understand, such as positions or colors

**Comment by Dixon10** [comment]
<img width="414" alt="Pin Config" src="https://user-images.githubusercontent.com/43393562/212443877-37f02db8-4d94-4684-9c7b-c4a500daabe5.png">

<img width="234" alt="Screen Shot 2023-01-13 at 10 32 32 PM" src="https://user-images.githubusercontent.com/43393562/212450725-2394d5d2-a865-44ad-80b1-cb7227aef55c.png">
When you say you want color coding/position placement for the buttons do you mean in the code or on the pin config? Also idk how to change the color on either of those.

**Comment by caljay98** [comment]
By colors I meant the actual button colors on the steering wheel. Those have not been picked out yet, so I dont think there is much you can do right now
