### ISSUE TITLE
Add 16 position dial input

### ISSUE THREAD

**Issue by caljay98** [gopher-motorsports/steering_wheel_module_23#2]
Take in 4 GPIO inputs and convert them into a single 16-position output. Store this value in a GopherCAN variable and send it to the PLM for logging with GSense

**Comment by Dixon10** [comment]
Doesn't the code block where I say:
rot_result = (rot_sw3_in << 3) | (rot_sw2_in << 2) | (rot_sw1_in << 1) | rot_sw0_in;
update_and_queue_param_u8(&sw_dial, rot_result);

already take the 4 GPIO inputs and turn them into an integer from 0-15 and send it to the PLM through CAN?
Also sorry for falling off the face of the planet during break, I'll try and be more consistent if you assign me any other tasks in the future

**Comment by caljay98** [comment]
That technically does block, but it is just the time to excecute the math and the function which shouldn't be too long at all. That code looks good

**Comment by Dixon10** [comment]
wait so what am I supposed to change? cause that's written in the mainloop function

**Comment by caljay98** [comment]
This is complete then, I can resolve this comment
